### ISSUE TITLE
The second corresponds to the measured throughput in kbps.

### ISSUE THREAD

**Issue by godka** [NGnetLab/Live-Video-Streaming-Challenge#7]
See in https://github.com/NGnetLab/Live-Video-Streaming-Challenge/blob/master/dataset/README.md

> The second corresponds to the measured throughput in kbps.

Emmm... kbps, really? Or, you mean, mbps?

**Comment by bupt-steven** [comment]
mbps

**Comment by godka** [comment]
Roger that
